language: node_js

node_js:
- 6.1

before_install:
    - cd app

cache:
    directories:
        - node_modules
        
install:
    - npm install

script:
    - npm version
    - npm run test

notifications:
  email:
  - 'aegloff@hsr.ch'
