language: node_js

node_js:
- 6.1

before_install:
    - cd app

cache:
    directories:
        - node_modules
        
install:
    - npm install

test:
    - npm test

script:
    - npm version

notifications:
  email:
  - 'aegloff@hsr.ch'